### ISSUE TITLE
check all example usage and vignette documentation

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/fiphde#144]
as we have updated the `fiphde` API its possible that some of our usage examples may have become stale.

we should check all the examples in documentation and code in vignette to confirm that all runs as expected. this is especially important for some of the examples that have been wrapped in `\dontrun` .

**Comment by stephenturner** [comment]
Thanks for filing this issue. Lots of little issues fixed in draft PR #146. I left a few `FIXME`s in for you, mostly in glm.R, and one in utils. 

There's a warning getting thrown with `plot_forecast()`. I know _why_ it's happening, and it's not important. I tried fixing by passing a filtered tibble to geom_ribbon, but the legend gets messed up. I couldn't figure out how to return a ggplot2, where later printing that ggplot2 object will suppress the warning.

**Comment by vpnagraj** [comment]
done.
