### ISSUE TITLE
remove covariates argument from ts_fit_forecast

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/fiphde#158]
suggesting we drop the covariates argument from ts_fit_forecast

as it stands now, even though you can specify *names* of covariates, the only ones that are baked in are harcoded into a join to the `fiphde:::historical_severity` object:

https://github.com/signaturescience/fiphde/blob/main/R/forecast.R#L146

in other words, there is no way to actually get covariate data into this function. makes for a confusing API imo.

**Comment by stephenturner** [comment]
I understand. I suggest making this TRUE/FALSE. If TRUE it'll use the historical covariates in the model (default), if FALSE it won't. Otherwise, it's kind of hard-coded in there that we do use them. Which makes this rather inflexible (i.e., can't use for CLI, for instance, where currently use `covariates=NULL`).

**Comment by stephenturner** [comment]
See https://github.com/signaturescience/clifford/issues/9

**Comment by stephenturner** [comment]
closed in #170
