### ISSUE TITLE
improved ILI forecasting

### ISSUE THREAD

**Issue by vpnagraj** [signaturescience/fiphde#89]
the SigSci-CREG method uses count regression model to and forecast flu hospitalizations. the approach steps finds the best fitting model from a list of models, *all* of which currently include ILI as a predictor.  the modeling step uses "observed" ILI (a mix of reported ILI via FluView augmented with ILI Nearby Nowcast for 2 most recent weeks). however, in order to forecast into the future we need predicted values of ILI 1-4 weeks ahead for each geographic unit.

given the importance of ILI as a predictor for SigSci-CREG, we need to make sure we optimize the ILI forecasting as best we can. the current method for forecasting ILI uses an ARIMA approach:

https://github.com/signaturescience/fiphde/blob/main/R/forecast.R#L106-L296

note that up to now we have also operated under the assumption that it is better to fit the models on more recent data (because the dynamics of ILI activity are likely different during COVID-19 pandemic):

https://github.com/signaturescience/fiphde/blob/main/submission/submission.R#L25-L29

a few initial ideas to consider:

- alternate (S)ARIMA parameterization / restriction on parameter spaces
- include older data in training
- log (or logit?) transform on ILI prior to modeling (Lu and Meyer, doi:10.3390/ijerph17041381)
- dummy variables for holidays, aberrant weeks  (Lu and Meyer, doi: 10.3390/ijerph17041381)
- beta regression ((Lu and Meyer, doi: 10.3390/ijerph17041381)
- autoregressive neural network approach (Kandula and Shaman, doi: 10.1016/j.epidem.2019.01.002)

there are certainly lots of other ideas to consider. and because ILI was the target of previous FluSight challenges, there is plenty of literature on ILI forecasting methods.

one important thing to keep in mind is that we will need to think through how to evaluate what effect (if any) these alternate methods has on 1) ILI forecast performance and 2) downstream SigSci-CREG forecast performance. that evaluation will probably need to involve measuring performance across a range of time points (and geographic units) to see what is *generally* the most effective method.

**Comment by chulmelowe** [comment]
I think you're correct Stephen, we did decide to continue using the ILI forecasts that we've been using since, at a high level, there doesn't appear to be much to choose between the different methods. I'm still trying to make time to dig into the data and determine if there are any useful patterns we might be able to exploit and to rerun the simulation using the data that Kundala and Shaman used to see if we get the same results with the neural network forecasts. In my mind, that's the biggest outstanding question: Why didn't the neural network model, which performed better than most other models in the previous literature, perform better on the current data set? My suspicion is that it has something to do with COVID, but that's only a hypothesis and it needs testing. Unfortunately, I'm trying to do two peoples' work at the moment on other projects and haven't been able to circle back to this. If we want to close this issue, I suggest we open an issue for the K&S replication and maybe another issue for the review of the counterfactual forecasts at a more detailed level than I've been able to so far just so that they stay on the radar.

Christopher A. Hulme-Lowe, Ph.D.
Statistician
***@***.***<http://www.signaturescience.com/>
8329 N. Mopac Expressway
Austin, TX 78759
512.583.2398|651.270.5814 ***@***.***
